// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: markdown.proto

package puzzlemarkdownservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MarkdownClient is the client API for Markdown service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarkdownClient interface {
	Apply(ctx context.Context, in *MarkdownText, opts ...grpc.CallOption) (*MarkdownHtml, error)
}

type markdownClient struct {
	cc grpc.ClientConnInterface
}

func NewMarkdownClient(cc grpc.ClientConnInterface) MarkdownClient {
	return &markdownClient{cc}
}

func (c *markdownClient) Apply(ctx context.Context, in *MarkdownText, opts ...grpc.CallOption) (*MarkdownHtml, error) {
	out := new(MarkdownHtml)
	err := c.cc.Invoke(ctx, "/puzzlemarkdownnservice.Markdown/Apply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarkdownServer is the server API for Markdown service.
// All implementations must embed UnimplementedMarkdownServer
// for forward compatibility
type MarkdownServer interface {
	Apply(context.Context, *MarkdownText) (*MarkdownHtml, error)
	mustEmbedUnimplementedMarkdownServer()
}

// UnimplementedMarkdownServer must be embedded to have forward compatible implementations.
type UnimplementedMarkdownServer struct {
}

func (UnimplementedMarkdownServer) Apply(context.Context, *MarkdownText) (*MarkdownHtml, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedMarkdownServer) mustEmbedUnimplementedMarkdownServer() {}

// UnsafeMarkdownServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarkdownServer will
// result in compilation errors.
type UnsafeMarkdownServer interface {
	mustEmbedUnimplementedMarkdownServer()
}

func RegisterMarkdownServer(s grpc.ServiceRegistrar, srv MarkdownServer) {
	s.RegisterService(&Markdown_ServiceDesc, srv)
}

func _Markdown_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkdownText)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarkdownServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/puzzlemarkdownnservice.Markdown/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarkdownServer).Apply(ctx, req.(*MarkdownText))
	}
	return interceptor(ctx, in, info, handler)
}

// Markdown_ServiceDesc is the grpc.ServiceDesc for Markdown service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Markdown_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "puzzlemarkdownnservice.Markdown",
	HandlerType: (*MarkdownServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _Markdown_Apply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "markdown.proto",
}
