// Copyright 2022 puzzlemarkdownservice authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.14.0
// source: markdown.proto

package puzzlemarkdownservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarkdownText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *MarkdownText) Reset() {
	*x = MarkdownText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_markdown_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkdownText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkdownText) ProtoMessage() {}

func (x *MarkdownText) ProtoReflect() protoreflect.Message {
	mi := &file_markdown_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkdownText.ProtoReflect.Descriptor instead.
func (*MarkdownText) Descriptor() ([]byte, []int) {
	return file_markdown_proto_rawDescGZIP(), []int{0}
}

func (x *MarkdownText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type MarkdownHtml struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Html string `protobuf:"bytes,1,opt,name=html,proto3" json:"html,omitempty"`
}

func (x *MarkdownHtml) Reset() {
	*x = MarkdownHtml{}
	if protoimpl.UnsafeEnabled {
		mi := &file_markdown_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkdownHtml) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkdownHtml) ProtoMessage() {}

func (x *MarkdownHtml) ProtoReflect() protoreflect.Message {
	mi := &file_markdown_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkdownHtml.ProtoReflect.Descriptor instead.
func (*MarkdownHtml) Descriptor() ([]byte, []int) {
	return file_markdown_proto_rawDescGZIP(), []int{1}
}

func (x *MarkdownHtml) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

var File_markdown_proto protoreflect.FileDescriptor

var file_markdown_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x15, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x22, 0x0a, 0x0c, 0x4d, 0x61, 0x72, 0x6b, 0x64,
	0x6f, 0x77, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x22, 0x0a, 0x0c, 0x4d,
	0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x48, 0x74, 0x6d, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x74, 0x6d, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x32,
	0x5d, 0x0a, 0x08, 0x4d, 0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x51, 0x0a, 0x05, 0x41,
	0x70, 0x70, 0x6c, 0x79, 0x12, 0x23, 0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x61, 0x72,
	0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x75, 0x7a, 0x7a,
	0x6c, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x48, 0x74, 0x6d, 0x6c, 0x42, 0x6e,
	0x0a, 0x22, 0x69, 0x6f, 0x2e, 0x64, 0x76, 0x61, 0x75, 0x6d, 0x6f, 0x72, 0x6f, 0x6e, 0x2e, 0x70,
	0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x42, 0x1a, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x4d, 0x61, 0x72, 0x6b,
	0x64, 0x6f, 0x77, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64,
	0x76, 0x61, 0x75, 0x6d, 0x6f, 0x72, 0x6f, 0x6e, 0x2f, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x6d,
	0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_markdown_proto_rawDescOnce sync.Once
	file_markdown_proto_rawDescData = file_markdown_proto_rawDesc
)

func file_markdown_proto_rawDescGZIP() []byte {
	file_markdown_proto_rawDescOnce.Do(func() {
		file_markdown_proto_rawDescData = protoimpl.X.CompressGZIP(file_markdown_proto_rawDescData)
	})
	return file_markdown_proto_rawDescData
}

var file_markdown_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_markdown_proto_goTypes = []interface{}{
	(*MarkdownText)(nil), // 0: puzzlemarkdownservice.MarkdownText
	(*MarkdownHtml)(nil), // 1: puzzlemarkdownservice.MarkdownHtml
}
var file_markdown_proto_depIdxs = []int32{
	0, // 0: puzzlemarkdownservice.Markdown.Apply:input_type -> puzzlemarkdownservice.MarkdownText
	1, // 1: puzzlemarkdownservice.Markdown.Apply:output_type -> puzzlemarkdownservice.MarkdownHtml
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_markdown_proto_init() }
func file_markdown_proto_init() {
	if File_markdown_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_markdown_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkdownText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_markdown_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkdownHtml); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_markdown_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_markdown_proto_goTypes,
		DependencyIndexes: file_markdown_proto_depIdxs,
		MessageInfos:      file_markdown_proto_msgTypes,
	}.Build()
	File_markdown_proto = out.File
	file_markdown_proto_rawDesc = nil
	file_markdown_proto_goTypes = nil
	file_markdown_proto_depIdxs = nil
}
